### ISSUE TITLE
Performance & Lazy loading

### ISSUE THREAD

**Issue by voxelbustersold** [konfer-be/cliam#8]
Thanks lot for the package! It's awesome!

Currently it's nearly taking around 1sec to load the module. While this is fine for normal server, it adds cold starts on serverless functions.

Are there any options available to make sure it loads only used services rather than loading all service modules (I need sendgrid alone)?

**Comment by steve-lebleu** [comment]
Thanks ! Very true on this point.I didn't see right away that some dependencies had so many sub-dependencies, and I didn't try to optimize this aspect later.

So no, currently this kind of thing is not supported, but it's clearly something that could be worked on in future releases. For now, my initial need is met and I don't know when I'll push further, but I'll look into these issues at the same time. Otherwise, don't hesitate to fork the project or do a PR if you have something interesting to propose ;-)

**Comment by steve-lebleu** [comment]
HI @voxelbustersold ,

I did a lot of changes recently, if you not did it yourself before, it's done ;-)
